[package]
name = "tauri-plugin-aptabase"
version = "0.5.1"
license = "MIT"
description = "Tauri Plugin for Aptabase: Open Source, Privacy-First and Simple Analytics for Mobile, Desktop and Web Apps"
authors = ["Guilherme Oenning"]
edition = "2021"
rust-version = "1.70"
readme = "README.md"
repository = "https://github.com/aptabase/tauri-plugin-aptabase"
exclude = ["/examples", "/webview-dist", "/webview-src", "/node_modules"]
links = "tauri-plugin-aptabase"

[dependencies]
tauri = "2.1"
tokio = "1"
futures = "0.3"
serde = "1"
serde_json = "1"
reqwest = { version = "0.12", features = ["json"] }
time = { version = "0.3", features = ["formatting"] }
os_info = "3"
rand = "0.8"
log = "0.4"
sys-locale = "0.3"

[build-dependencies]
tauri-plugin = { version = "2.0", features = ["build"] }
